<?php
return array (
  'mxcms' => 
  array (
    's1' => 
    array (
      'logo1' => '/template/mxone/mxstatic/image/logo.png',
      'logo2' => '/template/mxone/mxstatic/picture/logo.png',
      'logo3' => '/template/mxone/mxstatic/picture/logo.png',
      'pic' => '/template/mxone/mxstatic/image/loading.gif',
      'pic1' => '/template/mxone/mxstatic/image/loading.gif',
      'gg' => '独家制作',
      'searchwd' => '搜索电影、电视剧、综艺、动漫',
      'sm' => '本站所有内容均来自互联网分享站点所提供的公开引用资源，未提供资源上传、存储服务。',
    ),
    's2' => 
    array (
      'searchhoticon' => '1',
      'diysearchhoticon' => 'iconfont icon-paihangbang1 phb phb',
      'descjiaobiao' => '1',
      'descjiaobiaowenzi' => 'IF101资源站',
      'qzslt' => '0',
      'pcgddh' => '1',
      'gddhbg' => '0',
      'gddhbgdm' => '',
      'zhiboym' => '1',
      'diyliveicon' => 'iconfont icon-zhibo',
      'nav' => '1',
      'navids' => '1,2,3,4',
      'navdiy1' => '1',
      'navdiyn1' => 'if101免费高清无水印采集站',
      'navdiyu1' => 'https://www.ahlly.com/',
      'navdiy2' => '1',
      'navdiyn2' => '重复视频合并插件',
      'navdiyu2' => 'https://www.ahlly.com/',
      'navdiy3' => '1',
      'navdiyn3' => 'TG站长群',
      'navdiyu3' => 'https://www.ahlly.com/',
      'navdiy4' => '1',
      'navdiyn4' => '推荐播放器',
      'navdiyu4' => 'https://www.ahlly.com/',
      'navdiy5' => '0',
      'navdiyn5' => '',
      'navdiyu5' => '',
      'navdiy6' => '0',
      'navdiyn6' => '',
      'navdiyu6' => '',
      'sydh' => '0',
      'sydhicon' => 'icon-all',
      'sydhall' => '',
      'daohangid' => 'parent',
      'pcdhicon' => '0',
      'iconmr' => 'iconfont icon-kongbaiwendang',
      'num1' => '1',
      'icon1' => 'icon-cate-dy',
      'num2' => '2',
      'icon2' => 'icon-cate-ds',
      'num3' => '3',
      'icon3' => 'icon-cate-zy',
      'num4' => '4',
      'icon4' => 'icon-cate-dm',
      'num5' => '5',
      'icon5' => 'iconfont icon-zixun2',
      'num6' => '6',
      'icon6' => '',
      'num7' => '7',
      'icon7' => '',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
      'diy1icon' => 'iconfont icon-zidingyiquyu',
      'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
      'diy2icon' => 'iconfont icon-zidingyiquyu',
      'diy3' => '0',
      'diy3name' => '',
      'diy3url' => '',
      'diy3icon' => 'iconfont icon-zidingyiquyu',
      'wapsydh' => '1',
      'yxjcd' => '1',
      'yxjdiy' => '0',
      'cdbjys' => '',
      'iconbjys' => '',
      'iconztys' => '',
      'iconbjglys' => '',
      'fontqh' => '1',
      'yjqh' => '1',
      'liuyan' => '1',
      'topic' => '0',
      'dbdh' => '1',
      'todaygx' => '1',
      'todaycss' => '#FF0000',
      'listphb' => '1',
      'listphbname' => '月榜',
      'listphbtj' => '',
      'listphbby' => 'hits_month',
      'indextopic' => '1',
      'sytopicicon' => '0',
      'sytopiciconcss' => '#FF0000;',
      'indextopicnum' => '4',
      'indexart' => '1',
      'syzixunicon' => '0',
      'syzixuniconcss' => '#FF0000',
      'indexartid' => '5',
      'indexartnum' => '6',
      'bigslide' => '1',
      'slidetj' => '9',
      'slidenum' => '8',
      'slidediy1' => '0',
      'slidediy1name' => '',
      'slidediy1fname' => '',
      'slidediy1pic' => '',
      'slidediy1url' => '',
      'slidediy2' => '0',
      'slidediy2name' => '',
      'slidediy2fname' => '',
      'slidediy2pic' => '',
      'slidediy2url' => '',
      'slidediy3' => '0',
      'slidediy3name' => '',
      'slidediy3fname' => '',
      'slidediy3pic' => '',
      'slidediy3url' => '',
      'hot' => '1',
      'hoticon' => '0',
      'hoticoncss' => '#FF0000',
      'hotlevels' => '',
      'hotlevel' => '1,5,9',
      'hotall' => 'all',
      'rebocss' => 'rebo',
      'vipcss' => 'vip',
      'tuijiancss' => 'tuijian',
      'yugao' => '1',
      'yugaoicon' => '1',
      'yugaoshoucang' => '0',
      'yugaoicons' => 'icon-tv',
      'yugaoiconcss' => '#FF0000',
      'yugaoname' => '电影预告',
      'yugaoall' => '1',
      'yugaowenzi' => '1',
      'yugaotip1' => '即将上映',
      'yugaotip2' => '即将上映',
      'yugaotip3' => '即将上映',
      'logtype' => '1,2,3,4',
      'lbiconkg' => '0',
      'lbiconcss' => '#FF0000',
      'lbiconmr' => 'iconfont icon-kongbaiwendang',
      'lbnum1' => '1',
      'lbicon1' => 'icon-cate-dy',
      'lbnum2' => '2',
      'lbicon2' => 'icon-cate-ds',
      'lbnum3' => '3',
      'lbicon3' => 'icon-cate-zy',
      'lbnum4' => '4',
      'lbicon4' => 'icon-cate-dm',
      'lbnum5' => '5',
      'lbicon5' => 'iconfont icon-zixun2',
      'lbnum6' => '6',
      'lbicon6' => '',
      'lbnum7' => '7',
      'lbicon7' => '',
      'lbnum8' => '8',
      'lbicon8' => '',
      'listlevel' => '',
      'new' => '1',
      'newicon' => '0',
      'newiconcss' => '#FF0000',
      'newids' => 'parent',
      'mryj' => '0',
      'tagkg' => '1',
      'tzzt' => '0',
      'xght' => '1',
      'about' => '1',
      'dbtop' => '1',
      'doubanlj' => '1',
      'user' => '1',
      'shoucang' => '1',
      'comment' => '1',
      'detailen' => '1',
      'miniplay' => '1',
      'tc' => '1',
      'tc_noti' => '<p>欢迎使用MxoneV10魔改主题模板</p>
<p>本次更新内容</p>
<p>移步尽心Q群查看更新</p>
<p>感谢你的支持,MXoneV10魔改版模板购买ahlly.com</p>',
      'bftip' => '1',
      'bftips1' => '不要轻易相信视频中的任何广告，谨防上当受骗',
      'bftips2' => '如遇视频无法播放或加载速度慢，可尝试切换播放节点或者切换解析',
      'play' => 
      array (
        'jxxl' => '',
        'indextccont' => '',
      ),
      'app' => '0',
      'app_url' => '',
      'app_url2' => '',
      'wz0' => '1',
      'web1' => 'www.98dou.cn',
      'wz01' => '1',
      'web2' => 'www.98big.com',
      'wz2' => '1',
      'web3' => '',
      'wz3' => '0',
      'web4' => '',
      'wz4' => '0',
      'web5' => '',
      'wz5' => '0',
    ),
    's5' => 
    array (
      'wapdaohangid' => 'parent',
      'iconmr' => 'iconfont icon-kongbaiwendang',
      'num1' => '1',
      'icon1' => 'icon-cate-dy',
      'num2' => '2',
      'icon2' => 'icon-cate-ds',
      'num3' => '3',
      'icon3' => 'icon-cate-zy',
      'num4' => '4',
      'icon4' => 'icon-cate-dm',
      'num5' => '5',
      'icon5' => 'iconfont icon-zixun2',
      'num6' => '6',
      'icon6' => '',
      'num7' => '7',
      'icon7' => '',
      'num8' => '8',
      'icon8' => '',
      'num9' => '9',
      'icon9' => '',
      'num10' => '10',
      'icon10' => '',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
      'diy1icon' => 'iconfont icon-zidingyiquyu',
      'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
      'diy2icon' => 'iconfont icon-zidingyiquyu',
    ),
    's6' => 
    array (
      'wapdaohangid' => 'parent',
      'num1' => '1',
      'icon1' => 'icon-cate-dy',
      'num2' => '2',
      'icon2' => 'icon-cate-ds',
      'num3' => '3',
      'icon3' => 'icon-cate-zy',
      'num4' => '4',
      'icon4' => 'icon-cate-dm',
      'num5' => '5',
      'icon5' => 'iconfont icon-zixun2',
      'iconmr' => 'iconfont icon-kongbaiwendang',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
      'diy1icon' => 'iconfont icon-zidingyiquyu',
      'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
      'diy2icon' => 'iconfont icon-zidingyiquyu',
    ),
    's7' => 
    array (
      'hotpxb' => '1',
      'hotlevel' => '',
      'hotnum' => '10',
      'zztjb' => '1',
      'zztjlevel' => 'all',
      'zztjnum' => '10',
      'diytopidslevel' => '',
      'diytopidsnum' => '10',
      'diytopids' => '1,2,3,4',
      'iconmr' => 'iconfont icon-zhibo',
      'num1' => '1',
      'icon1' => 'icon-cate-dy',
      'num2' => '2',
      'icon2' => 'icon-cate-ds',
      'num3' => '3',
      'icon3' => 'icon-cate-zy',
      'num4' => '4',
      'icon4' => 'icon-cate-dm',
      'num5' => '5',
      'icon5' => '',
      'num6' => '6',
      'icon6' => '',
    ),
    's3' => 
    array (
      'adqj' => '0',
      'aadqj' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位05</h3></div>',
      'ad1' => '0',
      'aad1' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位01</h3></div>',
      'addb' => '0',
      'aaddb' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位06</h3></div>',
      'ad2' => '0',
      'aad2' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位02</h3></div>',
      'ad22' => '0',
      'aad22' => '',
      'ad3' => '0',
      'aad3' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-top: 20px;"> <h3 style="text-align: center;">广告位03</h3></div>',
      'ad4' => '0',
      'aad4' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位04</h3></div>',
    ),
    's4' => 
    array (
      'shier' => '0',
      'ctrl' => '0',
      'right' => '0',
      'mode' => '0',
      'pbtips' => '你知道的太多了',
      'tbdm' => '1',
      'tbdmtips' => '<meta name="referrer" content="always"> 
<meta name="referrer" content="no-referrer" />',
      'dbdm' => '0',
      'dbdmtips' => '统计代码',
      'stylediy' => '0',
      'stylecss' => '',
    ),
  ),
);